### ISSUE TITLE
Missing Registration Checkbox

### ISSUE THREAD

**Issue by rushsteve1** [pichalite/nodebb-theme-slick#33]
The check boxes on the terms page during registration have `opacity: 0` so are invisible. Easily solved by removing the rule from `.checkbox input`.
Can be temporarily overridden using custom css and the rule:
```css
.checkbox input {
    opacity: unset;
}
```
